// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt52au_YvLq41u47KFG0rnrCq8svUa38E',
    appId: '1:820220165217:web:05b02116dc5d8f6d49be20',
    messagingSenderId: '820220165217',
    projectId: 'ironbook-2048',
    authDomain: 'ironbook-2048.firebaseapp.com',
    storageBucket: 'ironbook-2048.firebasestorage.app',
    measurementId: 'G-278Y39NJ5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHuNGof-7gxA0aroAgyXECYD9u9OgV8Lk',
    appId: '1:820220165217:android:d59a91abf97d014149be20',
    messagingSenderId: '820220165217',
    projectId: 'ironbook-2048',
    storageBucket: 'ironbook-2048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfa7d2s3B1jEL6KMsVY_da6ndT0r50gqQ',
    appId: '1:820220165217:ios:683a6d3b65ff8acc49be20',
    messagingSenderId: '820220165217',
    projectId: 'ironbook-2048',
    storageBucket: 'ironbook-2048.firebasestorage.app',
    iosBundleId: 'com.example.ironbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt52au_YvLq41u47KFG0rnrCq8svUa38E',
    appId: '1:820220165217:web:3bcf440e5712f29349be20',
    messagingSenderId: '820220165217',
    projectId: 'ironbook-2048',
    authDomain: 'ironbook-2048.firebaseapp.com',
    storageBucket: 'ironbook-2048.firebasestorage.app',
    measurementId: 'G-LVQ4SCB8G1',
  );
}
